development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: depot_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: depot_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: depot
  pool: 5
  username: root
  password:
